[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api-proxy/:splat"
status = 200

[[redirects]]
from = "/kobutor/*"
to = "https://kobutor.s3.us-east-1.amazonaws.com/:splat"
status = 200
force = true